### ISSUE TITLE
Can not sign in with user name containing non-ascii chars

### ISSUE THREAD

**Issue by mapcentia** [sashuk/geocloud2#6]
Its possible to create new user with non-ascii chars. Like `Martin Høgh`. The database will become `martin_hgh` as expected.
But its not possible to login with `Martin Høgh` (but you can with `martin_hgh`)
I believe this is a GC2 issue.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/geocloud2/commit/7fd5cd0fa8cd63d8ba9d370c8ab4d823a1ac1dc8

![screenname](https://user-images.githubusercontent.com/1390758/58608577-cae30a80-82d6-11e9-9523-f46a4bf05075.gif)
