### ISSUE TITLE
Snapshots are listed in configurations

### ISSUE THREAD

**Issue by mapcentia** [sashuk/geocloud2#7]
![image](https://user-images.githubusercontent.com/3850918/59627059-a8a61500-913d-11e9-8d2a-df6921ddb271.png)

The KeyValue API now has two filter metods, which may be helpful:

`https://swarm.gc2.io/api/v2/keyvalue/horsens?like=state_snapshot%&paths=id;title;token;schema;database;host;userId;anonymous&filter='{anonymous}'='false'`

`like=state_snapshot%` is a wildcard filter on the key name.
`filter='{anonymous}'='false'` is a JSON WHERE clause for the values.

And
`paths=id;title;token;schema;database;host;userId;anonymous` can select which properties you want in the result.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/geocloud2/commit/be96c62f36225ebe69259a6eab5d4396e75a4451 (the `like` parameter was added when selection configurations, as well as using a prefix for all configurations in the key-value storage.

**Comment by sashuk** [comment]
> The KeyValue API now has two filter metods, which may be helpful:
> 
> `https://swarm.gc2.io/api/v2/keyvalue/horsens?like=state_snapshot%&paths=id;title;token;schema;database;host;userId;anonymous&filter='{anonymous}'='false'`
> 
> `like=state_snapshot%` is a wildcard filter on the key name.
> `filter='{anonymous}'='false'` is a JSON WHERE clause for the values.
> 
> And
> `paths=id;title;token;schema;database;host;userId;anonymous` can select which properties you want in the result.

Great, thanks!
